apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicate: 1
  selector:
    matchlabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      container:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-server
spec:
  selector:
    app: nodeapp
  type: loadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
